import Link from "next/link";

import { sessionPricingAction } from "@/app/organizer/actions";
import { PricingSummary } from "@/components/organizer/pricing-summary";
import { Badge } from "@/components/ui/badge";
import { buttonStyles } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import { fieldControlStyles, FieldLabel } from "@/components/ui/field";
import { CURRENCY_VALUES, ROUTES } from "@/config/site";
import { minorUnitsToInputValue } from "@/features/events/money";
import { hasMinimumMembershipRole } from "@/lib/authorization";
import { getDatabase } from "@/lib/database";
import { requireEventSessionAccess } from "@/lib/event-authorization";
import { getSessionPublicationReadiness } from "@/server/events/event-session-service";

export default async function SessionPricingPage({ params, searchParams }: { params: Promise<{ organizationSlug: string; eventSlug: string; sessionId: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const scope = await params;
  const notices = await searchParams;
  const path = ROUTES.organizerSessionPricing(scope.organizationSlug, scope.eventSlug, scope.sessionId);
  const { membership, event } = await requireEventSessionAccess(scope, path);
  const { eventSession, coverage } = await getSessionPublicationReadiness(getDatabase(), scope.sessionId);
  const canManage = hasMinimumMembershipRole(membership.role, "ADMIN") && eventSession.status === "DRAFT" && ["DRAFT", "PUBLISHED"].includes(event.status);
  const action = sessionPricingAction.bind(null, scope);
  const assignmentBySection = new Map(eventSession.sectionPricing.map((assignment) => [assignment.sectionId, assignment.priceTierId]));

  return <section className="bg-slate-50 py-12 sm:py-16"><Container>
    <Link href={ROUTES.organizerSession(scope.organizationSlug, scope.eventSlug, scope.sessionId)} className="text-sm font-semibold text-slate-600 hover:text-slate-950">← Back to session</Link>
    {notices.error ? <p className="mt-5 rounded-2xl bg-red-50 p-4 text-sm text-red-800" role="alert">{notices.error}</p> : null}{notices.success ? <p className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-800">Pricing saved.</p> : null}
    <div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Badge className="bg-violet-50 text-violet-800 ring-violet-600/15">{eventSession.status}</Badge><h1 className="mt-4 text-4xl font-black tracking-[-0.05em] text-slate-950">Session pricing</h1><p className="mt-2 text-slate-600">One tier per section. Zero-price tiers are intentionally supported; negative prices are forbidden.</p></div>{!canManage ? <Badge className="bg-amber-50 text-amber-800 ring-amber-600/15">READ ONLY</Badge> : null}</div>
    <div className="mt-8 grid gap-7 lg:grid-cols-[0.9fr_1.1fr]">
      <div className="space-y-6">
        {canManage ? <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-slate-950">Add price tier</h2><form action={action} className="mt-5 grid gap-4 sm:grid-cols-2"><input type="hidden" name="intent" value="create-tier" /><div><FieldLabel htmlFor="new-tier-name">Name</FieldLabel><input id="new-tier-name" name="name" className={`${fieldControlStyles} mt-2`} required /></div><div><FieldLabel htmlFor="new-tier-code">Code</FieldLabel><input id="new-tier-code" name="code" className={`${fieldControlStyles} mt-2 uppercase`} required /></div><div><FieldLabel htmlFor="new-tier-price">Price</FieldLabel><input id="new-tier-price" name="price" inputMode="decimal" defaultValue="0.00" className={`${fieldControlStyles} mt-2`} required /></div><div><FieldLabel htmlFor="new-tier-currency">Currency</FieldLabel><select id="new-tier-currency" name="currency" className={`${fieldControlStyles} mt-2`}>{CURRENCY_VALUES.map((currency) => <option key={currency}>{currency}</option>)}</select></div><div className="sm:col-span-2"><FieldLabel htmlFor="new-tier-description">Description</FieldLabel><input id="new-tier-description" name="description" className={`${fieldControlStyles} mt-2`} maxLength={500} /></div><button className={buttonStyles({ size: "sm", className: "sm:col-span-2" })}>Add tier</button></form></section> : null}
        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-slate-950">Price tiers</h2><div className="mt-5 space-y-4">{eventSession.priceTiers.length > 0 ? eventSession.priceTiers.map((tier, index) => canManage ? <article key={tier.id} className="rounded-2xl border border-slate-200 p-4"><form action={action} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="intent" value="update-tier" /><input type="hidden" name="priceTierId" value={tier.id} /><input name="name" defaultValue={tier.name} className={fieldControlStyles} aria-label={`${tier.code} tier name`} required /><input name="code" defaultValue={tier.code} className={`${fieldControlStyles} uppercase`} aria-label={`${tier.code} tier code`} required /><input name="price" defaultValue={minorUnitsToInputValue(tier.priceMinor, tier.currency)} className={fieldControlStyles} aria-label={`${tier.code} tier price`} required /><select name="currency" defaultValue={tier.currency} className={fieldControlStyles} aria-label={`${tier.code} tier currency`}>{CURRENCY_VALUES.map((currency) => <option key={currency}>{currency}</option>)}</select><input name="description" defaultValue={tier.description ?? ""} className={`${fieldControlStyles} sm:col-span-2`} aria-label={`${tier.code} tier description`} /><button className={buttonStyles({ variant: "outline", size: "sm", className: "sm:col-span-2" })}>Save tier</button></form><div className="mt-3 flex flex-wrap gap-2">{index > 0 ? <form action={action}><input type="hidden" name="intent" value="move-tier" /><input type="hidden" name="priceTierId" value={tier.id} /><button name="direction" value="up" className={buttonStyles({ variant: "ghost", size: "sm" })}>Move up</button></form> : null}{index < eventSession.priceTiers.length - 1 ? <form action={action}><input type="hidden" name="intent" value="move-tier" /><input type="hidden" name="priceTierId" value={tier.id} /><button name="direction" value="down" className={buttonStyles({ variant: "ghost", size: "sm" })}>Move down</button></form> : null}<form action={action} className="flex items-center gap-2"><input type="hidden" name="intent" value="delete-tier" /><input type="hidden" name="priceTierId" value={tier.id} /><label className="text-xs text-slate-500"><input type="checkbox" name="confirmation" value="delete" required /> Confirm</label><button className={buttonStyles({ variant: "ghost", size: "sm", className: "text-red-700" })}>Delete unused</button></form></div></article> : <article key={tier.id} className="rounded-2xl border border-slate-200 p-4"><h3 className="font-bold text-slate-950">{tier.name} · {tier.code}</h3><p className="mt-1 text-sm text-slate-600">{minorUnitsToInputValue(tier.priceMinor, tier.currency)} {tier.currency}</p></article>) : <p className="text-sm text-slate-600">No tiers have been configured.</p>}</div></section>
      </div>
      <div className="space-y-6"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-slate-950">Coverage summary</h2><div className="mt-5"><PricingSummary tiers={coverage.tiers} totalSellable={coverage.totalSellable} pricedSellable={coverage.pricedSellable} unpricedSellable={coverage.unpricedSellable} /></div></section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-slate-950">Assign sections</h2><p className="mt-2 text-sm text-slate-600">Every section containing active sellable seats needs exactly one tier before publication.</p><form action={action} className="mt-5 space-y-3"><input type="hidden" name="intent" value="assign-sections" />{coverage.sections.map((section) => <label key={section.sectionId} className="grid gap-2 rounded-2xl border border-slate-200 p-4 sm:grid-cols-[1fr_12rem] sm:items-center"><span><span className="block font-bold text-slate-950">{section.sectionName} · {section.sectionCode}</span><span className="mt-1 block text-xs text-slate-500">{section.sellable} sellable · {section.blocked} blocked</span></span><select name={`section:${section.sectionId}`} defaultValue={assignmentBySection.get(section.sectionId) ?? ""} className={fieldControlStyles} disabled={!canManage}><option value="">Unpriced</option>{eventSession.priceTiers.map((tier) => <option key={tier.id} value={tier.id}>{tier.name} · {tier.code}</option>)}</select></label>)}{canManage ? <button className={buttonStyles({ className: "w-full" })}>Save section pricing</button> : null}</form></section></div>
    </div>
  </Container></section>;
}
